### ISSUE TITLE
Page generator - Localized Assets

### ISSUE THREAD

**Issue by rmiklautz** [commercelayer/contentful-commerce#3]
Hey,

I am using commercelayer together with commercelayer and jekyll.

Unfortunately i receive following error:

jekyll 3.8.5 | Error: undefined method `each' for nil:NilClass

config.yml:

```
contentful:
  spaces:
    - en-US:
        space: xxx
        access_token: xxxx
        all_entries: true
        cda_query:
          locale: "en-US"
    - it:
        space: xxx
        access_token: xxx
        all_entries: true
        cda_query:
          locale: "it"
```

Any ideas?
